### ISSUE TITLE
PyTorch implementation code

### ISSUE THREAD

**Issue by CharlesEmileG** [kaichen-z/RAD#1]
Hi, I really appreciate the work done on this project, I think it is very interesting. I'd love to look at the implementation code and try to replicate the methods used. You've mentioned that "this repository provides the official PyTorch implementation code, data and models of the RAD". Let me know if it would be possible to add it!

**Comment by kaichen-z** [comment]
Thank you for your interest. We are currently finalizing our data preparation, and the code will be available by the end of this week.

**Comment by CharlesEmileG** [comment]
Perfect thank you!

**Comment by kaichen-z** [comment]
Hello, we've uploaded the final version of our data along with the proposed pose estimation method referenced in our paper. If you need any further information, please let me know. Otherwise, feel free to close this issue.

**Comment by kaichen-z** [comment]
As there are no further questions, we will proceed to close this issue.
